
automation_sequence:
  - id: 0
    name: "Start"
    command: ""
    delay: 0.0
    repeat: false
    next_id: [1]

  - id: 1
    name: "Ox Main Valve Open"
    command: "411"  # Ox Main On
    delay: 0.0
    repeat: false
    next_id: [2]

  - id: 2
    name: "Fuel Main Valve Open"
    command: "421"  # Fuel Main On
    delay: 0.1
    repeat: false
    next_id: [3]

  - id: 3
    name: "Ox Purge Valve Open"
    command: "431"  # Ox Purge On
    delay: 0.0
    repeat: false
    next_id: [4]

  - id: 4
    name: "Fuel Purge Valve Open"
    command: "441"  # Fuel Purge On
    delay: 0.1
    repeat: false
    next_id: [5]

  - id: 5
    name: "Spark Plug On"
    command: "801"  # Spark Plug On
    delay: 0.3
    repeat: false
    next_id: [6]

  - id: 6
    name: "Igniter Ox Valve Open"
    command: "541"  # Igniter Ox On
    delay: 0.1
    repeat: false
    next_id: [7]

  - id: 7
    name: "Igniter Fuel Valve Open"
    command: "401"  # Igniter Fuel On
    delay: 6.0
    repeat: false
    next_id: [8]

  - id: 8
    name: "Turn Off Spark Plug"
    command: "800"  # Spark Plug Off
    delay: 2.0
    repeat: false
    next_id: [9]

  - id: 9
    name: "Close Igniter Fuel Valve"
    command: "400"  # Igniter Fuel Off
    delay: 0.0
    repeat: false
    next_id: [10]

  - id: 10
    name: "Close Igniter Ox Valve"
    command: "540"  # Igniter Ox Off
    delay: 1.0
    repeat: false
    next_id: [11]

  - id: 11
    name: "Ox Purge Valve Close"
    command: "430"  # Ox Purge Off
    delay: 0.0
    repeat: false
    next_id: [12]

  - id: 12
    name: "Fuel Purge Valve Close"
    command: "440"  # Fuel Purge Off
    delay: 0.0
    repeat: false
    next_id: [13]

  - id: 13
    name: "Fuel Main Valve Close"
    command: "420"  # Fuel Main Off
    delay: 0.25
    repeat: false
    next_id: [14]

  - id: 14
    name: "Ox Main Valve Close"
    command: "410"  # Ox Main Off
    delay: 0.0
    repeat: false
    next_id: []