automation_sequence:
  - id: 0
    name: "Start Moonshine Short"
    command: ""
    delay: 0.0
    repeat: false
    next_id: [1]

  - id: 1
    name: "Ematch"
    command: "221"  # Ematch On
    delay: 0.5
    repeat: false
    next_id: [2]

  - id: 2
    name: "Ox Main Open"
    command: "201"  # Ox Iso Valve Open
    delay: 0.5
    repeat: false
    next_id: [3]

  - id: 3
    name: "Fuel Main Open"
    command: "211"  # Fuel Iso Valve Open
    delay: 0.1
    repeat: false
    next_id: [4]

  - id: 4
    name: "Ematch Off"
    command: "220"  # Ematch Off
    delay: 5.0
    repeat: false
    next_id: [5]

