automation_sequence:
  - id: 1
    name: "Ox Main Open"
    command: "201"
    delay: 0.0
    repeat: false
    next_id: [2]

  - id: 2
    name: "Fuel Main Open"
    command: "211"
    delay: 0.0
    repeat: false
    next_id: []