B1:
  calculations: []
B2:
  calculations:
    - C1 * C4
    - C3
    - C4
    - '50'
B3:
  calculations: []
B4:
  calculations: []
B5:
  calculations: []
B6:
  calculations:
    - C1 + C2
B7:
  calculations: []
B8:
  calculations: []
B9:
  calculations: []
B10:
  calculations: []
